# Generated by Django 3.1.1 on 2020-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20200930_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, default='Item Description', null=True),
        ),
    ]
